name: gaussian_splatting
channels:
  - conda-forge
  - defaults
dependencies:
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn